library(shiny)
library(shinyWidgets)
library(shinycssloaders)
library(shinyBS)
library(colourpicker)
library(readxl)
library(dplyr)
library(magrittr)
library(DT)
library(sf)
library(ggplot2)
library(plotly)
library(leaflet)
library(leaflet.extras)
data_earth <- read_excel("www/earthquake.xlsx") %>%
  select("latitude","longitude","depth","mag","magType","place","year","month")
Turkiye <- st_read("www/Turkiye.shp")